### ISSUE TITLE
Ekran końca gry - Wygląd

### ISSUE THREAD

**Issue by Qawery** [Qawery/Polygon_Projekt_20Z#20]
Zaprojektuj wygląd ekrany końca gry.
Powinien zawierać:
-komunikat o zakończeniu rozgrywki (zwycięstwo lub przegrana),
-wynik,
-przycisk do restartowania gry,
-przycisk powrotu do menu głownego,
-ewentualnie jakieś dekoracje.

Wersje dla wygranej i przegranej mogą różnić się tylko napisem, albo być zupełnie inne.
Jak wolisz.

**Comment by Qawery** [comment]
Wydziel grafiki i wrzuć je do projektu.

**Comment by K-Antonina** [comment]
Skończone.

**Comment by K-Antonina** [comment]
Jeśli ktoś ma czas, to oddam przerabianie ekranu, bo ostatnio wypadło parę rzeczy asap. Ale jak nie ma kto tego wziąć to to zrobię w miarę możliwości.

**Comment by Selthen** [comment]
Ja mogę się zająć tymi modyfikacjami.
