### ISSUE TITLE
Menu główne - Wygląd

### ISSUE THREAD

**Issue by Qawery** [Qawery/Polygon_Projekt_20Z#21]
Zaprojektuj wygląd menu głównego.

Będzie składał się z trzech ekranów:
-główny,
-how to play,
-credits.

Ekran główny powinien zawierać:
-tytuł gry,
-przycisk rozpoczęcia gry
-przycisk how to play
-przycisk creditsów
-przycisk wyjścia
-ewentualnie jakieś dekoracje.

Ekran creditsów i how to play powinny zawierać:
-tytuł,
-treść,
-przycisk wstecz.

**Comment by K-Antonina** [comment]
Skończone.
