### ISSUE TITLE
Zaprojektować działanie broni

### ISSUE THREAD

**Issue by Qawery** [Qawery/Polygon_Projekt_20Z#23]
Zaprojektuj całokształt działania broni w grze, w szczególności:
-ograniczenie lub nie amunicji
-przeładowanie,
-typy,
-sposób zdobywania,
-wpływ na charakter rozgrywki.

Przedstaw kilka rozwiązań wraz z atutami i wadami.

**Comment by Qawery** [comment]
Filmiki do inspiracji:
https://www.youtube.com/watch?v=J5IdHqg2rT8
https://www.youtube.com/watch?v=1GeA3rdfEXU
https://www.youtube.com/watch?v=JDWsOutcE5E

**Comment by frotto440** [comment]
Proponuję zrobić 3 rodzaje broni. Player na początku ma standardową broń z najmniejszym damagem, dwie pozostałe będą rozłożone na mapie. Przejście przez broń oznacza zamianę broni. Broń, która była w ręce, może być ponownie podniesiona. Broń początkowa miałaby mały damage ale szybciej strzela. Proponuję zrobić jedną broń, którą można najwolniej (z najmniejszą częstotliwością) strzelać, lecz będzie miała ona największy damage i podczas strzału będzie lekki odrzut (taka bazuka). Trzecia broń może czymś pomiędzy wcześniej wspomnianymi - czyli damage większy od początkowej ale mniejszy od bazuki i podobnie z częstotliwością strzelania. Żeby różne poziomy damagu miały sens trzeba zmienić, że Enemies nie giną na jeden strzał.

**Comment by Qawery** [comment]
Z uwagi na krótki czas pozostały do showcase od razu zrobiłem nowy issue.
