### ISSUE TITLE
Zaprojektować działanie przeciwników

### ISSUE THREAD

**Issue by Qawery** [Qawery/Polygon_Projekt_20Z#24]
Zaprojektuj całokształt działania przeciwników w grze, w szczególności:
-typy,
-zachowania,
-sposoby pojawiania się,
-jak ich pokonać,
-wpływ na charakter rozgrywki.

Przedstaw kilka rozwiązań wraz z atutami i wadami.

**Comment by piotr0sawicki** [comment]
Proponuję, aby przeciwnicy:
-pojawiali się w ściśle określonych miejscach
-poruszali się wzdłuż jakiejś drogi (np. miedzy 2 punktami), do czasu aż w zasięgu ich wzroku nie pojawi się player (ewentualna reakcja na strzały i kroki w pobliżu)
-widzieli tylko to co jest przed nimi w określonym zasięgu
-w momencie zobaczenia playera zaczynali go gonić, do momentu aż ucieknie poza pewien dystans (są wolniejsi od playera)
-gdy player znajdzie się w zasięgu strzału i był zauważony, przeciwnik zaczyna do niego strzelać 
-aby ich pokonać należy dotrzeć do pewnego punktu- w przyszłości będzie możliwe zrobienie paru scen
-zadanie wystarczającej ilości obrażeń powoduje śmierć przeciwnika

**Comment by Qawery** [comment]
1. Ile i jakie typy przeciwników mają być w grze? Czym mają się od siebie różnić?
2. Co to znaczy "aby ich pokonać należy dotrzeć do pewnego punktu"?
3. Czym "zadanie wystarczającej ilości obrażeń powoduje śmierć przeciwnika" różni się od tego co mamy obecnie?

**Comment by piotr0sawicki** [comment]
Ad1 Myślę, że większość przeciwników będzie tego samego typu. Można jednak dodać typ "ulepszony" tzn. więcej HP, wolniejsze poruszanie oraz inny rodzaj broni (np. obszarowy dmg / szybkostrzelność), jednak on będzie występował relatywnie rzadko. Można również dodać jakiegoś Boss-a.
Ad2 Ten warunek jest związany bardziej z końcem gry, co nie jest moją działką.
Ad3 Niczym, jednak uważam, że jest to dobre rozwiązanie - nie widzę innej opcji.

**Comment by Qawery** [comment]
Filmik do inspiracji:
https://www.youtube.com/watch?v=yuOObGjCA7Q

**Comment by piotr0sawicki** [comment]
Przeciwników proponuję podzielić wstępnie na 3 typy (nazwy robocze:)):
1. ShotgunEnemy : 
- średnio szybkie poruszanie się
- broń średniego zasięgu której pociski latają szybko i zadają średnie obrażenia.
- gdy player znajdzie się w zasięgu strzału- przestają się poruszać i zaczynają strzelać.
2. ZombieEnemy :
- bardzo mały zasięg rażenia broni (najlepiej broń biała)
- szybkie poruszanie oraz małe obrażenia
- średnia ilość HP
- najliczniejszy rodzaj przeciwnika
3. BossEnemy : 
- praktycznie nieograniczony zasięg broni, jednak wolne pociski zadające duże obrażenia
- nie porusza się
- dużo punktów życia
- może wybuchać ginąc

Powinni być spawnowani w falach, w określonych miejscach.

**Comment by Qawery** [comment]
Brzmi spoko.
Założę nowe zadanie.
