### ISSUE TITLE
Zaprojektować mechanikę poruszania się

### ISSUE THREAD

**Issue by Qawery** [Qawery/Polygon_Projekt_20Z#27]
Zastanowić się jakie możliwości poruszania się powinien mieć gracz.
Czy tylko chodzenie, czy może również skakanie lub latanie.
Czy powinien mieć jakieś specjalne umiejętności i jak miałyby one działać?

Przedstaw kilka rozwiązań wraz z atutami i wadami.

**Comment by SzyMan1337** [comment]
Moja propozycja:
- gracz może skakać  
- potrafi się skradać (np. trzymając klawisz shift chodzi wolniej i jego kroki nie są słyszalne) 

Dodatkowo zastanawiam się nad:
- kucaniem 
- rozglądaniem prawo lewo po wciśnięciu q, e

Jeśli chodzi o jakieś umiejętności i bonusy to gracz mógłby je podnosić z losowych miejsc mapy. Mogłyby to być np:
- zwiększone życie
- podwójny lub wyższy skok
- nieskończona amunicja
- większy damage z broni
- szybsze poruszanie

Na mapie mogłyby znajdować się również jakieś pechowe bonusy dla gracza.

**Comment by Qawery** [comment]
Skakanie można dodać i będzie pasować do prawie wszystkiego.

Reszta zależy od gameplay'u, jeśli będziemy robić skradankę to ok, a jesli nie to są niepotrzebne.
("Rozglądanie prawo lewo" - rozumiem że chodzi o wychylanie się np. zza rogu.)

Podnoszenie bonusów z planszy to temat na oddzielny issue.

Czy zastanawiałeś się nad następującymi rzeczami:
-czy można w powietrzu sterować postacią,
-wielorotny skok,
-uniki (aka. dash),
-latanie,
-sprint,
-podciąganie się do góry przy trafieniu w krawędź,
-chodzenie po drabinach,
-teleportacja.

Obejrzyj sobie jakie możliwości poruszania dają następujące gry i czy chcemy czymś z nich się zainspirować:
Dishonored, Mirror's Edge, Doom Eternal, Deep Rock Galactic, Batman: Arkham Asylum.

**Comment by SzyMan1337** [comment]
Trochę przejrzałem i proponuje:
-  postać w locie porusza się tam gdzie obecnie spogląda (czyli jedynie zmienianie kierunku myszką),
- podwójny skok,
- sprint,
- dash, 

Dodatkowo spróbować zaimplementować teleportację.

**Comment by Qawery** [comment]
Nie rozumiem o co chodzi z tym pomysłem że postać leci tam gdzie spogląda.
Skoro mamy ruch na boki to postać powinna co najwyżej kontynuować lot w kierunku w którym się poruszała przed skokiem.

Osobiście uważam że sprint i dash nawzajem się wykluczają.

"Spróbować zaimplementować teleportację" nie mówi nic jak ma ona działać, i czemu ma służyć.


Patrząc na obecny stan prac proponuję zaimplementować tylko bezwładność w locie i dash.
