### ISSUE TITLE
Model areny

### ISSUE THREAD

**Issue by Qawery** [Qawery/Polygon_Projekt_20Z#31]
Stwórz element z których ma składać się arena na której będzie odbywała się rozgrywka:
- [x] Kilka sekcji muru, które można łączyć ze sobą.
- [x] Podłoże.
- [x] Ewentualnie jakieś obiekty do wrzucenia do środka jako przeszkody.

Elementy mogą być modelami zrobionymi przez Ciebie lub prymitywami Unity z nałożonymi teksturami, metoda dowolna.
Dodatkowo pobaw się oświetleniem sceny i sky box'em.

**Comment by K-Antonina** [comment]
Skończone.
