### ISSUE TITLE
Model podstawowego przeciwnika

### ISSUE THREAD

**Issue by Qawery** [Qawery/Polygon_Projekt_20Z#5]
Stwórz model dla podstawowego przeciwnika i dodaj go do projektu.
Niech jego rozmiar będzie w okolicach dorosłego człowieka (1.5 - 2 m).
Wrzuć go na swoją scenę testową i zobacz czy poprawnie się wyświetla.
Pamiętaj że jedna jednostka Unity to jeden metr w świecie rzeczywistym, jest to istotne dla fizyki.

**Comment by K-Antonina** [comment]
Skończone.
