### ISSUE TITLE
Pierwsza animacja

### ISSUE THREAD

**Issue by Qawery** [Qawery/Polygon_Projekt_20Z#6]
Dodaj animacje bezczynności (idle) do modelu przeciwnika.
Animacja ta ma odtwarzać się w pętli od momentu pojawienia się przeciwnika.
Możesz zaimportować animacje z zewnętrznego programu lub stworzyć je wewnątrz silnika.
Wrzuć na swoją scenę testową zanimowany model.

Do uruchomienia animacji użyj komponentu animator i stwórz dla niego animation controller.

**Comment by K-Antonina** [comment]
Skończone.
