### ISSUE TITLE
Znaleźć i podpiąć brakujące dźwięki

### ISSUE THREAD

**Issue by Qawery** [Qawery/Polygon_Projekt_20Z#81]
Nalezy znaleźć w internecie (albo zrobić samemu) następujące dźwięki:
- [x] muzyka do menu głównego,
- [x] dźwięk wciśnięcia przycisku w menu głównym,
- [ ] dźwięki ataku dla nowych broni.

Następnie należy je podpiąć w odpowiednie miejsca w projekcie.
Pamiętać o poprawnej licencji.

**Comment by Qawery** [comment]
Przy przypinaniu nowych dźwięków pamiętać o przydzieleniu im odpowiednich mixerów audio (od muzyki lub od dźwięków).

**Comment by Selthen** [comment]
Pozostałość przeniesiona do innego issue.
