### ISSUE TITLE
Wygląd menu pauzy

### ISSUE THREAD

**Issue by Qawery** [Qawery/Polygon_Projekt_20Z#88]
Powinno zawierać:
- [x] Tytuł.
- [x] Przycisk powrotu do menu głównego.
- [x] Przycisk wznowienia gry.
- [x] Ewentualnie jakieś dekoracje.

**Comment by Selthen** [comment]
W issue odnośnie logiki menu pauzy jest jeszcze przycisk opcji, więc należy go chyba tu również uwzględnić.

**Comment by K-Antonina** [comment]
Skończone.
