### ISSUE TITLE
Poruszanie gracza

### ISSUE THREAD

**Issue by Qawery** [Qawery/Polygon_Projekt_20Z#9]
Stwórz placeholderową postać gracza za pomocą kapsułki i doklej do niej kamerę.
Zaproponuj architekturę poruszania i rozglądania się (jako komentarz pod tym issue).
Zaimplementuj uzgodnione ze mną rozwiązanie.
Stwórz prefab postaci gracza i umieść go na swojej scenie testowej.
Podepnij poruszanie za pomocą klawiszy i rozglądanie za pomocą myszy.

**Comment by SzyMan1337** [comment]
Proponuje, rozglądanie się w czterech kierunkach poruszając myszką. Przy czym rozglądanie się w lewo i prawo powoduje obrót postaci a w góre i dół tylko kamery. Ruch do przodu odbywał by się w kierunku obserwacji. Do tyłu byłby cofaniem się, postać by się nie obracała. Dodatkowo ruch w prawo i lewo odbywał by się bez rotacji postaci. Mogę również zaimplementować skok i jakieś inne sposoby poruszania się jak na przykład domyślny bieg i skradanie po wciśnieciu dannego klawisza.

**Comment by Qawery** [comment]
Funkcjonalności chodzenia i rozglądania są ok.
Skakaniem, bieganiem i skradaniem zajmiemy się później.

Jeśli chodzi o architekturę, to zastanów się na jakie komponenty podzielić implementacje i na jakich gameobject'ach mają się one znajdować.
Ze swojej strony mogę zaproponować dwa sposoby:
1. Szybki
Jeden komponent na postaci gracza, który odbiera input i steruje postacią.
Da się go bardzo szybko zrobić, ale nie jest to "poprawny" sposób robienia w prawdziwych grach.
Na ten moment polecam tę wersję.
2. Dobry
Trzy komponenty: odbierający input, sterujący postacią i spinający te dwa ze sobą.
Na postaci leży tylko komponent sterujący postacią.
Komponent odbierający input przetwarza tylko klawisze na predefiniowane eventy sterowania.
Komponent spinający odpowiada za przetłumaczenie eventów sterowania na wywołania funkcji komponentu sterowania postacią.
Bardziej skomplikowane podejście, ale umożliwia modyfikacje i rozszerzenia.
Wymieniam jeśli chciałbyś coś trudniejszego.

Oczywiście jak chcesz możesz wymysleć coś własnego.
Zastanów się też jakich mechanizmów Unity będziesz używał 
(może być Character Controller, ale też coś własnego np. z wykorzystaniem fizyki).

Jak wymyślisz rozwiązanie napisz mniej więcej jakie będą klasy, funkcje i kiedy będą wywoływane.
Jak chcesz to możemy się umówić na call'a, wtedy będę mógł wyjaśnić dokładniej o co Mi chodzi.

**Comment by Qawery** [comment]
Wygląda spoko.
1. Daj dwie linie odstępu między usingami a nazwą klasy.
2. Daj dwie linie odstępu między zmiennymi a metodami.
3. Zmień nazwę skryptu na "PlayerController" albo coś takiego.
4. Zrób prefab postaci gracza i wrzuć go do folderu "Prefabs".
5. Dodaj opadanie postaci za pomocą grawitacji (komponent "Rigidbody").
6. Zrób na mnie merge requesta.

**Comment by Qawery** [comment]
Dorzuciłem na Twoją scenę mury i rampę do testowania spadania.
Wykonaj jeszcze punkt 4 i 6.
